# Generated by Django 5.1.3 on 2024-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("Customer_Name", models.CharField(max_length=100)),
                ("Customer_ID", models.IntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Loan_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Loan_Type", models.TextField()),
            ],
        ),
    ]
